PROMPT_V1 = (
    "You're a medical expert in text classification of informational needs of patients with {disease}. "
    "Your task is to analyze a new text and determine if it belongs to one of the existing clusters based on their descriptions. "
    "If the new text does not fit into any of the existing clusters, you must classify it as a 'NEW' one"
    "\n\n** EXISTING CLUSTER DESCRIPTIONS: **\n{formatted}\n\n"
    "\n\n** NEW TEXT TO CLASSIFY: **\nTITLE:\n{title}\nSUBMISSTION:\n{text}\n\n"
    "\n\n** INSTRUCTIONS: **\n\n"
    "1. **Analyze:** Carefully read the 'NEW TEXT TO CLASSIFY' and understand its main topic, content, and intent."
    "2. **Compare:** Compare the meaning and themes of the new text to the descriptions of each existing cluster."
    "3. **Classify:**:\n."
    "   * If the new text strongly aligns with the description of an existing cluster, assign it to that cluster.\n"
    "   * If the new text does not fit well into any of the existing clusters, assign it to 'NEW' cluster.\n"
    "4. **Prioritize assigning to an existing cluster:** Always try to look for an existing cluster first before deciding it's a new one. \n\n"
    "Now, assign the new text provided to you to an existing cluster."
)

PROMPT_V2 = (
    "You're a medical expert in text classification of informational needs "
    "of patients with {disease}. "
    "Your task is to analyze a text and classify it into the single best-matching "
    "informational need from the list below."
    "\n\n** KNOWN INFORMATIONAL NEEDS: **\n{formatted}\n\n"
    "\n\n** INSTRUCTIONS: **\n\n"
    "1. **Analyze:** Carefully read the text below and identify its main topic "
    "and the core question or information the author is seeking.\n"
    "2. **Distinguish intent from framing:** Many posts mix emotional language "
    "with concrete clinical, logistical, or practical questions. "
    "Focus on what the author is *primarily asking for or seeking*, "
    "not the emotional tone surrounding it.\n"
    "   - If the post asks a specific clinical, surgical, screening, or genetic "
    "question (even if expressed with anxiety), classify it under the relevant "
    "clinical/medical category.\n"
    "   - Classify as 'Psychosocial, Identity, and Mental Health Support' ONLY "
    "when the *primary purpose* of the post is to express emotions, seek "
    "emotional support, discuss identity/body image, or process grief/anxiety "
    "without a specific medical question driving the post.\n"
    "   - If the post asks for provider or facility recommendations, classify "
    "under the category matching the *type of care* being sought (e.g., "
    "reconstruction surgeon -> Breast Reconstruction; therapist -> Psychosocial), "
    "not 'Navigating the Healthcare System' unless the post is primarily about "
    "insurance, referrals, administrative processes, or systemic navigation.\n"
    "3. **Classify:** Assign the text to the single best-matching informational need.\n"
    "\n\n** TEXT TO CLASSIFY: **\nTITLE:\n{title}\nTEXT:\n{text}\n\n"
    "Now, classify the text."
)

PROMPT_V3 = (
    "You're a medical expert in text classification of informational needs of patients with {disease}. "
    "Your task is to analyze a new text and determine which of the existing clusters it belongs to based on their descriptions. "
    "\n\n** EXISTING CLUSTER DESCRIPTIONS: **\n{formatted}\n\n"
    "\n\n** NEW TEXT TO CLASSIFY: **\nTITLE:\n{title}\nSUBMISSION:\n{text}\n\n"
    "\n\n** INSTRUCTIONS: **\n\n"
    "1. **Analyze:** Carefully read the 'NEW TEXT TO CLASSIFY' and understand its primary intent, core question, and overarching theme. "
    "Many posts contain multiple themes (e.g., emotional distress mixed with clinical questions), but you must identify the MAIN reason the author wrote the post.\n"
    "2. **Compare:** Compare the core meaning and main theme of the new text to the descriptions of each existing cluster.\n"
    "3. **Holistic Intent:** Look at the post as a whole. Does the author primarily seek emotional validation, community support, or coping strategies (Psychosocial)? Or are they primarily seeking factual, logistical, or medical information (e.g., Clinical Decision-Making, Navigating the Healthcare System)? Choose the category that best answers their primary need.\n"
    "4. **Classify:** Assign the text to the single best-matching existing cluster based on your analysis.\n\n"
    "Now, assign the new text provided to you to the most appropriate existing cluster."
)

PROMPT_V4 = (
    "You are a medical expert in classifying the informational needs of patients "
    "with {disease} from online forum posts.\n\n"
    "** INFORMATIONAL NEED CATEGORIES: **\n{formatted}\n\n"
    "** INSTRUCTIONS: **\n\n"
    "1. Read the post and identify the author's DOMINANT informational need — "
    "what they most need from the community. Many posts touch multiple topics; "
    "select the single category that best captures the primary need.\n\n"
    "2. Psychosocial vs. medical/clinical categories — apply this test:\n"
    "   - Ask yourself: 'Would the most helpful response be empathy and solidarity, "
    "or specific medical/factual information?'\n"
    "   - Posts centered on FEELINGS — anxiety, regret, fear, identity, coping, "
    "'has anyone else felt this way?' — belong in 'Psychosocial, Identity, and "
    "Mental Health Support', even if medical topics are mentioned as context.\n"
    "   - Posts seeking a SPECIFIC MEDICAL ANSWER — about screening, surgery options, "
    "genetic results, medications — belong in the relevant medical category, "
    "even if the author expresses worry.\n\n"
    "3. Additional category boundaries:\n"
    "   - 'Hormonal Health, Menopause, and HRT': when HRT, menopause symptoms, "
    "or hormonal side effects are the PRIMARY subject, not merely one factor "
    "in a broader surgical decision.\n"
    "   - 'Financial Navigation, Insurance, and Advocacy': costs, insurance coverage, "
    "billing disputes, or legislation affecting coverage — distinct from general "
    "healthcare system navigation.\n"
    "   - 'Emerging Risks, Research, and Misinformation': questions about "
    "non-established risk factors, novel research findings, or alternative medicine "
    "claims not part of standard clinical guidelines.\n\n"
    "** POST TO CLASSIFY: **\n"
    "TITLE: {title}\n"
    "TEXT: {text}\n\n"
    "Classify this post into exactly one informational need category."
)
