#!/usr/bin/env bash
# Start a notebook server here or on the GPU box.
#
#   ./gdanschin_runtime/jupyter.sh --local          serve on this laptop
#   ./gdanschin_runtime/jupyter.sh --remote         serve on the GPU box, tunnelled here
#   ./gdanschin_runtime/jupyter.sh --tunnel         tunnel only, server already running
#   ./gdanschin_runtime/jupyter.sh --stop           stop the server on the GPU box
#   ./gdanschin_runtime/jupyter.sh --serve [PORT]   serve on THIS machine, foreground
#   ./gdanschin_runtime/jupyter.sh --set-password   set or change the password
#
# --serve is for when you are already sitting on the GPU box, in your own tmux:
# it serves from wherever it is run, with no ssh and no tunnel of its own.
# Default port is JUPYTER_REMOTE_PORT, since that is the one the tunnel from the
# laptop expects; pass a port to override.
#
# Access is by password, hashed with argon2 - never a token in a URL, and never
# the password itself on disk.
#
# The remote server binds to 127.0.0.1 and is reached through an SSH tunnel,
# never exposed on the box's network interface. That box is shared, and a
# notebook server is arbitrary code execution as you.
#
# Ports differ per machine (configs/jupyter.conf) so the tunnel's local end
# cannot collide with a server running here.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$HERE/.." && pwd)"
# shellcheck source=configs/jupyter.conf
source "$HERE/configs/jupyter.conf"
LOCAL_PORT="${JUPYTER_LOCAL_PORT:-8888}"
REMOTE_PORT="${JUPYTER_REMOTE_PORT:-8889}"

MODE="${1:---local}"
[[ "$MODE" == "-h" || "$MODE" == "--help" ]] && { sed -n '2,18p' "${BASH_SOURCE[0]}"; exit 0; }

# The hash lives in a .conf beside the other secrets. Jupyter itself needs a
# .py, so one is generated from the .conf immediately before launch, on
# whichever machine is serving. That way the hash never crosses a shell
# boundary: it is read from a file and written to a file on the same host,
# instead of being threaded through ssh, tmux and two levels of quoting.
PW_CONF="$HERE/configs/jupyter-password.conf"
GEN_CONF="$HERE/configs/jupyter_server_config.generated.py"

if [[ "$MODE" == "--set-password" ]]; then
    read -rsp "new notebook password: " pw1; echo
    read -rsp "repeat it: " pw2; echo
    [[ "$pw1" == "$pw2" ]] || { echo "they do not match" >&2; exit 1; }
    [[ -n "$pw1" ]] || { echo "empty password" >&2; exit 1; }
    umask 077
    # Single quotes on purpose: see the note in jupyter-password.conf.example.
    PW="$pw1" "$REPO/.venv/bin/python" - "$PW_CONF" <<'SET_PW_EOF'
import os, sys
from jupyter_server.auth import passwd
h = passwd(os.environ["PW"])
assert "'" not in h, "unexpected quote in hash"
with open(sys.argv[1], "w") as f:
    f.write("# Generated by jupyter.sh --set-password. Never commit this.\n")
    f.write(f"JUPYTER_PASSWORD_HASH='{h}'\n")
SET_PW_EOF
    chmod 600 "$PW_CONF"
    echo "written to ${PW_CONF#"$REPO/"} (mode 600)"
    echo "push it to the GPU box with: ./gdanschin_runtime/sync/sync.sh --push-secrets"
    exit 0
fi

if [[ ! -f "$PW_CONF" ]]; then
    echo "no password set yet" >&2
    echo "  ./gdanschin_runtime/jupyter.sh --set-password" >&2
    exit 1
fi

# Turn the .conf into the .py Jupyter reads. password_required matters: with
# the token disabled and no password demanded, the server would admit anyone
# who reaches the port.
write_jupyter_config() {
    local conf="$1" out="$2"
    # shellcheck disable=SC1090
    source "$conf"
    [[ -n "${JUPYTER_PASSWORD_HASH:-}" && "$JUPYTER_PASSWORD_HASH" != "paste-hash-here" ]] || {
        echo "no usable hash in $conf" >&2; return 1; }
    ( umask 077
      {
        echo "# Generated at launch from ${conf##*/}. Do not edit."
        echo "c.PasswordIdentityProvider.hashed_password = '$JUPYTER_PASSWORD_HASH'"
        echo "c.PasswordIdentityProvider.token = ''"
        echo "c.PasswordIdentityProvider.password_required = True"
      } > "$out" )
}

if [[ "$MODE" == "--serve" ]]; then
    [[ -x "$REPO/.venv/bin/jupyter" ]] || { echo "no jupyter in .venv (run setup_env.sh)" >&2; exit 1; }
    PORT="${2:-$REMOTE_PORT}"
    write_jupyter_config "$PW_CONF" "$GEN_CONF"
    echo "serving on 127.0.0.1:$PORT from $(hostname)  (Ctrl-C to stop)"
    echo "from the laptop, tunnel to it with: ./gdanschin_runtime/jupyter.sh --tunnel"
    exec "$REPO/.venv/bin/jupyter" notebook --config "$GEN_CONF" \
        --port "$PORT" --port-retries 0 --ip 127.0.0.1 --no-browser --notebook-dir "$REPO"
fi

if [[ "$MODE" == "--local" ]]; then
    [[ -x "$REPO/.venv/bin/jupyter" ]] || { echo "no jupyter in .venv (run setup_env.sh)" >&2; exit 1; }
    write_jupyter_config "$PW_CONF" "$GEN_CONF"
    echo "serving on http://127.0.0.1:$LOCAL_PORT  (Ctrl-C to stop)"
    exec "$REPO/.venv/bin/jupyter" notebook --config "$GEN_CONF" \
        --port "$LOCAL_PORT" --port-retries 0 --no-browser --notebook-dir "$REPO"
fi

# shellcheck source=remote.sh
source "$HERE/remote.sh" || exit 1
SSH=(ssh -i "$REMOTE_IDENTITY" -o BatchMode=yes)
REMOTE_LOG="$REMOTE_DIR/logs/jupyter.log"
REMOTE_CONFIGS="$REMOTE_DIR/gdanschin_runtime/configs"

case "$MODE" in
    --stop)
        echo "stopping the notebook server on $REMOTE_HOST"
        # Killing the tmux session, not `jupyter notebook stop`: that command
        # talks to the server's shutdown API and authenticates with a token.
        # There is no token any more, so it gets 403 and the server keeps running.
        "${SSH[@]}" "$REMOTE" "
            tmux kill-session -t notebook 2>/dev/null && echo 'stopped' || echo 'nothing was running'
            sleep 1
            # Brackets so the pattern cannot match this very command line:
            # pkill -f scans full command lines, including the shell ssh spawns
            # to run this, and killing that returns 255 from an apparent success.
            pkill -f '[j]upyter-notebook' 2>/dev/null || true"
        exit 0
        ;;
    --remote)
        echo "starting on $REMOTE_HOST:$REMOTE_PORT (bound to its localhost)"
        # Started inside tmux rather than with nohup: backgrounding over ssh
        # leaves the client waiting on the channel, so it hangs even though the
        # server came up fine. tmux also lets you attach and watch:
        # ssh to the box, then `tmux attach -t notebook`.
        "${SSH[@]}" "$REMOTE" "
            cd '$REMOTE_DIR'
            if [ ! -f '$REMOTE_CONFIGS/jupyter-password.conf' ]; then
                echo 'no password config on the remote; run sync.sh --push-secrets' >&2
                exit 1
            fi
            # Generated here, on the box: the hash is read from a local file and
            # written to a local file, so its '\$' never meets a shell.
            . '$REMOTE_CONFIGS/jupyter-password.conf'
            umask 077
            {
              echo \"c.PasswordIdentityProvider.hashed_password = '\$JUPYTER_PASSWORD_HASH'\"
              echo \"c.PasswordIdentityProvider.token = ''\"
              echo \"c.PasswordIdentityProvider.password_required = True\"
            } > '$REMOTE_CONFIGS/jupyter_server_config.generated.py' 
            # Outside the running/not-running branch on purpose: these are
            # excluded from the mirror, so nothing else creates them, and an
            # already-running server is no reason to leave them missing.
            mkdir -p '$REMOTE_DIR/logs' '$REMOTE_DIR/notebooks'
            if .venv/bin/jupyter notebook list 2>/dev/null | grep -q ':$REMOTE_PORT/'; then
                echo 'already running'
            else
                tmux kill-session -t notebook 2>/dev/null || true
                tmux new-session -d -s notebook \
                    \"cd '$REMOTE_DIR' && .venv/bin/jupyter notebook --config '$REMOTE_CONFIGS/jupyter_server_config.generated.py' \
                      --port $REMOTE_PORT --port-retries 0 --ip 127.0.0.1 \
                      --no-browser --notebook-dir '$REMOTE_DIR' 2>&1 | tee '$REMOTE_LOG'\"
                sleep 5
            fi"
        ;;
    --tunnel) ;;
    *) echo "unknown argument: $MODE" >&2; exit 2 ;;
esac

echo
echo "  open: http://127.0.0.1:$LOCAL_PORT/   (it will ask for the password)"
echo
# A stale tunnel or a local server on this port makes ssh fail to bind while
# everything still *looks* fine - requests quietly reach the wrong server.
if lsof -nP -iTCP:"$LOCAL_PORT" -sTCP:LISTEN >/dev/null 2>&1; then
    echo "port $LOCAL_PORT is already in use here, so the tunnel cannot bind." >&2
    echo "Close whatever holds it (often a leftover tunnel) and retry:" >&2
    lsof -nP -iTCP:"$LOCAL_PORT" -sTCP:LISTEN | tail -n +2 | awk '{print "  " $1, "pid", $2}' >&2
    exit 1
fi

echo "tunnelling localhost:$LOCAL_PORT -> $REMOTE_HOST:$REMOTE_PORT  (Ctrl-C to close)"
exec ssh -i "$REMOTE_IDENTITY" -N -L "$LOCAL_PORT:127.0.0.1:$REMOTE_PORT" "$REMOTE"
